[package]
name = "bj"
version = "0.1.0"
authors = ["Matthew"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cm = { path = "cm" }
itertools = "0.9.0"
