[package]
name = "cm"
version = "0.1.0"
authors = ["Matthew"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[dependencies]
strum = "0.18.0"
strum_macros = "0.18.0"
